name : Release
on: [workflow_dispatch]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    permission:
      contents: write
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
