name: Release
on: [workflow_dispatch]

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17-jdk
      options: --user root
    steps:
      - name: Install git on container
        run: |
          apt update
          apt install -y git
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Clean caches
        run: ./gradlew clean --stacktrace
      - name: Upload releases
        run: ./gradlew build curseforge github modrinth publish --stacktrace